language: go
env:
  - GO111MODULE=on
go:
  - '1.11.x'
  - '1.12.x'
  - 'tip'
os:
  - linux
  - osx
  # - windows # go get fails on windows. why??? https://travis-ci.com/shogo82148/s3ftpgateway/jobs/166842634

script: make test
