AWSTemplateFormatVersion: 2010-09-09
Description: S3 buckets for testing s3ftpgateway

Parameters:
  Bucket:
    Type: String
    Default: shogo82148-s3ftpgateway

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref Bucket
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 90
          Status: Enabled

  TestRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/shogo82148/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/s3ftpgateway
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - 'sts:TagSession'
      Policies:
        - PolicyName: Test
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource:
                  - !Sub "${TestBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - !Sub "${TestBucket.Arn}"

Outputs:
  TestRole:
    Value: !GetAtt TestRole.Arn
