name: test
on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        golang:
          - "1.16"
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: setup Go ${{ matrix.golang }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - name: setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"

      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure AWS Credentials
        uses: shogo82148/actions-aws-assume-role@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/shogo82148-s3ftpgateway-TestRole-IKN52H3UIP7Y
          role-session-tagging: true

      - name: test
        run: make test
        env:
          S3FS_TEST_BUCKET: shogo82148-s3ftpgateway
