name: test
on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        golang:
          - "1.18"
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Go ${{ matrix.golang }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang }}
          cache: true
      - name: setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"

      - id: check
        uses: shogo82148/actions-check-permissions@v1
      - name: Configure AWS Credentials
        if: steps.check.outputs.permission == 'write'
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/shogo82148-s3ftpgateway-TestRole-IKN52H3UIP7Y
          role-session-tagging: true

      - name: integrated test
        if: steps.check.outputs.permission == 'write'
        run: make test
        env:
          S3FS_TEST_BUCKET: shogo82148-s3ftpgateway

      - name: unit test
        if: steps.check.outputs.permission != 'write'
        run: make test

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - name: Check GoReleaser configure
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: check
